module.exports.authController = require('./admin/auth.controller')
module.exports.productController = require('./admin/product.controller')
module.exports.brandController = require('./admin/brand.controller')
module.exports.newController = require('./admin/new.controller')
module.exports.userController = require('./admin/user.controller')
